---
name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run yamllint
        run: |
          set +e
          yamllint -s .
          code=$?
          set -e
          if [ $code -eq 1 ]; then
            echo "yamllint found errors"
            exit 1
          else
            echo "yamllint finished with code $code (0=ok, 2=warnings)"
          fi

      - name: Run ansible-lint
        run: ansible-lint -p -v .
